baseURL: "https://taoy66.github.io/Portfolio/"
canonifyURLs: true
relativeURLs: false
languageCode: "en-us"
title: "Tao Yan"
theme: "PaperMod"


menu:
  main:
    - identifier: home
      name: Home
      url: ""
      weight: 10
    - identifier: project
      name: Project
      url: "project/"
      weight: 20
    - identifier: certificate
      name: Certificate
      url: "certificate/"
      weight: 30
    - identifier: experience
      name: Experience
      url: "experience/"
      weight: 40
    - identifier: search
      name: Search
      url: "search/"
      weight: 50

params:

  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production



  # Home Page Settings
  profileMode:
    enabled: true
    title: "Tao Yan"
    subtitle: "Hi 👋 I'm Tao, a mechanical engineer who creates, develops, and refines mechanical products and manufacturing systems from concept to production using engineering first principles. I bring hands-on expertise in biopharma manufacturing and product development—designing parts, selecting materials, creating technical drawings, and validating performance through design of experiments (DOE) and engineering analysis. In GMP pharma environments, I drove system design, commissioning, tech transfers, and troubleshooting across downstream equipment and automation to improve reliability and reduce repeat downtime."
    imageUrl: "Coverimages/avatar.JPG"
    imageWidth: 260
    imageHeight: 260
    imageTitle: "Tao Yan"

    #buttons:
    #  - name: "Resume"
    #   url: "resume/"

  # List View
  hideDescriptionInList: false

   # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:tao.tom.yan@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/tao-yan-5bb904190/"
    - name: "github"
      url: "https://github.com/taoy66"

 # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON


# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true