baseURL = "https://taoy66.github.io/tao-portfolio/"
languageCode = "en-us"
title = "Tao Yan"
theme = "PaperMod"

[pagination]
  pagerSize = 5

[params]
  # turn on the profile hero for HOME page
  [params.profileMode]
    enabled = true
    title = "Tao Yan"
    subtitle = """**Mechanical Design & R&D** • Additive Manufacturing • Heat Transfer
**AI-assisted Engineering** and reliable mechanism design"""
    imageUrl = "/images/avatar.jpg"
    imageWidth = 260
    imageHeight = 260
    imageTitle = "Tao Yan"

    # (Optional) big buttons under the subtitle
    [[params.profileMode.buttons]]
      name = "Resume"
      url = "/resume/"


  # social icons row under the hero
  [[params.socialIcons]]
    name = "email"
    url  = "tao.tom.yan@gmail.com"

  [[params.socialIcons]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/tao-yan-5bb904190/"

  [[params.socialIcons]]
    name = "github"
    url  = "https://github.com/taoy66"



# Top nav tabs -> separate pages
[menu]
  [[menu.main]]
    name = "Home"
    url  = "/"
    weight = 10

  [[menu.main]]
    name = "Experience"
    url  = "/experience/"
    weight = 20

  [[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 30

  [[menu.main]]
    name = "Skills"
    url  = "/skills/"
    weight = 40